version: '3.4'
services:
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  frontend:
    build:
      context: ./client
      target: dev
    volumes:
      - ./client/src:/app/src
      - ./client/index.html:/app/index.html
      - ./client/package.json:/app/package.json
      - ./client/tsconfig.json:/app/tsconfig.json
    command: yarn dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      VITE_API_URL:
  backend:
    build:
      context: ./server
      target: dev
    volumes:
      - ./server/src:/app/
      - ./server/package.json:/app/package.json
      - ./server/tsconfig.json:/app/tsconfig.json
      - ./server/nodemon.json:/app/nodemon.json
    command: yarn dev
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      MONGO_URL:
volumes:
 mongodb:
