version: '3.4'
services:
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  frontend:
    build:
      context: ./
      dockerfile: ./src/front/Dockerfile
      target: dev
    volumes:
      - .:/src
    command: yarn client
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
  backend:
    build:
      context: ./
      dockerfile: ./src/back/Dockerfile
      target: dev
    volumes:
      - .:/src
    command: yarn server
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://database/jobs
volumes:
 mongodb:
